Разметка главной страницы
htmlacademy-htmlcss/384107-technomart-29 pull request #2
Opened 2020-09-11 20:33 UTC by Feizerr

Создала разметку для главной страницы, добавила страницу каталога

2020-09-11 20:35 UTC, Feizerr commented on index.html
> +			<!-- элементы "Закладки" и "Вопросы" вызывают сомнение. пока сделала их в виде абзацев со спаном, т.к. количество закладок и товаров в корзине может меняться -->
Элементы "Закладки" и "Вопросы" вызывают сомнение. Пока сделала их в виде абзацев со спаном, т.к. количество закладок и товаров в корзине может меняться. Возможно, есть какой-то другой способ их разметить — более правильный

2020-09-11 20:37 UTC, Feizerr commented on index.html
> +  		<!-- Непонятно, как делать этот элемент-слайдер  -->
Здесь тоже есть сомнения: может, стоило сделать описание Доставки как вложенный список?

2020-09-11 20:39 UTC, Feizerr commented on index.html
> +  		<div>
На сайте подвал как бы разделен цветом на 2 части: синюю и темно-синюю. Можно ли его так же дивами разделить на 2 блока? Или лучше использовать другие теги/не делить вообще?

2020-09-12 12:35 UTC, craz3r requested changes

2020-09-12 12:35 UTC, craz3r commented on index.html
> +			<!-- элементы "Закладки" и "Вопросы" вызывают сомнение. пока сделала их в виде абзацев со спаном, т.к. количество закладок и товаров в корзине может меняться -->
Как раз в случаях когда количество пунктов в меню может изменяться, лучше применить верстку списком <ul>. Это вообще универсальный способ верстки однотипных элементов, в независимости от того, будет ли меняться их количество

2020-09-12 12:35 UTC, craz3r commented on index.html
> +			<p><a href="tel:+78125550555">+7 (812) 555-05-55</a><br>
<br> здесь не очень подходит, так как разделяет визуально разные блоки, обычно он используется для переноса текста. Здесь же лучше сделать телефон и адрес отдельными блоками

2020-09-12 12:35 UTC, craz3r commented on index.html
> +  		<!-- Непонятно, как делать этот элемент-слайдер  -->
Так как в блок "доставка" суть слайдер, значит в нем есть еще как минимум 2 похожих блока, что наталкивает на мысль сделать это списком. Управление слайдером в данном случае отдельный вопрос

2020-09-12 12:35 UTC, craz3r commented on index.html
> +  		<div>
Так делить можно (по сути по другому и не разделишь)

2020-09-12 12:35 UTC, craz3r commented on index.html
> +	  			<li>Материалы</li>
Элементы этого списка являются ссылками

2020-09-13 10:49 UTC, Feizerr commented on index.html
> +			<!-- элементы "Закладки" и "Вопросы" вызывают сомнение. пока сделала их в виде абзацев со спаном, т.к. количество закладок и товаров в корзине может меняться -->
Прости,не очень поняла, где должен быть список. Вот здесь https://up.htmlacademy.ru/htmlcss/29/module/2/book/2.5 написали, что у Техномарта закладки, корзина, поиск и ссылка оформления заказа не не могут быть объединены в список.  Поэтому я их в тег <p> и добавила. Или лучше исправить и все-таки всё в список засунуть?

И еще у меня вопрос был по тому, как оформить "Корзина: 0". Чтобы этот ноль менялся на нужную цифру в зависимость от количества товаров, добавленных в корзину. Полагаю, впоследствии это будет делаться с помощью скриптов. Но правильно ли я убрала сейчас ноль в спан?

2020-09-13 10:49 UTC, Feizerr commented on index.html
> +  		<!-- Непонятно, как делать этот элемент-слайдер  -->
Так?
<ul>
  				<li>
  					<a href="#">Доставка</a>
            <h3>Доставка</h3>
            <p>Мы с удовольствием доставим ваш товар прямо<br>
            к вашему подъезду совершенно бесплатно!<br>
            Ведь мы неплохо заработаем,<br>
            поднимая его на ваш этаж!</p>
  				</li>
  				<li>
  					<a href="#">Гарантия</a>
  				</li>
  				<li>
  					<a href="#">Кредит</a>
  				</li>
  			</ul>


Или лучше вынести описание доставки, гарантий и кредита в отдельный список?

2020-09-13 11:19 UTC, craz3r requested changes

2020-09-13 11:19 UTC, craz3r commented on index.html
> +			<!-- элементы "Закладки" и "Вопросы" вызывают сомнение. пока сделала их в виде абзацев со спаном, т.к. количество закладок и товаров в корзине может меняться -->
По поводу корзины и кнопки оформления заказа, здесь ты скорее права, я приводил, так сказать, более общий пример. А по поводу нуля в корзине, ты правильно сделала

2020-09-13 11:19 UTC, craz3r commented on index.html
> +  		<!-- Непонятно, как делать этот элемент-слайдер  -->
Лучше вынести в отдельный список, так как он и визуально расположен отдельно

2020-09-13 11:19 UTC, craz3r commented on index.html
> +	  			<li>Материалы</li>
Здесь все еще не поправлено

2020-09-13 13:11 UTC, merged