Создание Каталога
htmlacademy-htmlcss/384107-technomart-29 pull request #3
Opened 2020-09-13 18:16 UTC by Feizerr

Создала первую версию страницы "Каталог товаров". На главной поправила опечатку в названии города.

2020-09-13 18:31 UTC, Feizerr commented on catalog.html
> +        <h2>Сортировка:</h2>
Смотрела, как устроена сортировка на других сайтах. Увидела, что обычно её заворачивют в див, а вместо элементов списка используют спаны. Но мне показалось, что  способы сортировки похожи на список, поэтому разметила её так.

2020-09-13 18:31 UTC, Feizerr commented on catalog.html
> +          <!-- У последних двух пунктов вместо текста будут иконки стрелочек -->
Здесь тоже интересно. На сайте предлагается сортировка по типу, по функционалу и по убыванию. А затем две стрелочки, чтобы отсортировать по возрастанию/убыванию чего-то (наверное, цены). Я их добавила в качестве отдельных элементов списка. Но, возможно, стоило их добавить отдельно? Или вообще не добавлять, а использовать псевдоэлемент ::after?

2020-09-13 18:31 UTC, Feizerr commented on catalog.html
> +          </li>
При наведении на карточку товара появляются две кнопки "Купить" и "В закладки". Долго думала, как лучше их разметить, в итоге решила добавить в список, т.е. в каждую из карточек.

2020-09-13 18:31 UTC, Feizerr commented on catalog.html
> +  					<a>Каталог</a>
Здесь вообще непонятно, надо ли ставить ссылку на каталог или нет.

С одной стороны, по ТЗ мы создаем страницу каталога. С другой, судя по хлебным крошкам, это не сам каталог, а одна из его страниц: "Перфораторы". Правильно ли я понимаю, что в таком случае ссылка на каталог будет нужна? И нужно ли тогда переименовать страницу?

2020-09-14 07:05 UTC, craz3r requested changes

2020-09-14 07:05 UTC, craz3r commented on catalog.html
> +  					<a>Каталог</a>
Ты права, ссылка здесь нужна, так как сейчас мы находимся на внутренней странице каталога. Но переименовывать страницу не нужно, так как по сути все страницы каталога (перфораторы, дрели. etc) будут выглядеть одинаково, различаться будет только контент (это то что называется шаблонизацией, о ней вам ближе к концу расскажут)

2020-09-14 07:05 UTC, craz3r commented on catalog.html
> +        <h2>Сортировка:</h2>
На самом деле тут каждый делает как считает удобным, в данном случае список здесь выглядит логично, так как элементы однотипны

2020-09-14 07:05 UTC, craz3r commented on catalog.html
> +          <!-- У последних двух пунктов вместо текста будут иконки стрелочек -->
Сортировка в данном случае двойная, одна по некоторой категории (тип, цена, функционал), другая сортировочная. И их можно применять одновременно, потому лучше разнести их по разным спискам, как равнозначные. Псевдоэлемент здесь не нужен

2020-09-14 07:05 UTC, craz3r commented on catalog.html
> +          </li>
Правильно

2020-09-15 08:17 UTC, merged