Добавление контентных изображений
htmlacademy-htmlcss/384107-technomart-29 pull request #6
Opened 2020-09-20 19:37 UTC by Feizerr

Добавила все изображения в папку Img. Подключила контентные изображения в разметке.

2020-09-20 19:44 UTC, Feizerr commented on index.html
>      		</ul>
Не поняла, куда добавить второй слайд с дрелью. Как думаешь, может, вообще вынести слайдер в отдельный список, состоящий всего из двух элементов:  перфораторы и дрели?

2020-09-20 19:44 UTC, Feizerr commented on catalog.html
> +          <a class="main-header-logo footer-logo" href="index.html"><img src="img/logo-footer.svg" width="138" height="23" alt="Логотип компании Техномарт"></a>
В браузере теперь логотип в футере отображается странно. Текст выходит за красный фон. Это из-за стилей браузера?

2020-09-21 08:18 UTC, craz3r commented on index.html
>      		</ul>
По идее структура слайдера именно такой и должна быть, список с несколькими элементами (слайдами), из которых виден только текущий

2020-09-21 08:20 UTC, craz3r commented on catalog.html
> +          <a class="main-header-logo footer-logo" href="index.html"><img src="img/logo-footer.svg" width="138" height="23" alt="Логотип компании Техномарт"></a>
у тебя для ссылки footer-logo заданы стили, один из которых высота строки, так как ссылка - по умолчанию строчный элемент, то ее высота, как раз этим параметром и устанавливается. Поэтому с технической точки зрения ничего странного в таком поведении нет)

2020-09-21 08:22 UTC, craz3r requested changes
У меня отображаются не все картинки в разделе популярные производители
![Screen Shot 2020-09-21 at 11 22 17](https://user-images.githubusercontent.com/12268931/93745764-baa61b80-fbfc-11ea-9058-298fbdbbb5f7.png)

2020-09-22 10:59 UTC, merged